services:
  apache:
    container_name: apache_blog
    build:
      context: ./apache
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - php

  php:
    container_name: php_blog
    build:
      context: ./php
    volumes:
      - .:/var/www/html
    expose:
      - "9000"