services:
  # Service Mailpit (si vous en avez besoin)
  mailpit:
    image: axllent/mailpit
    container_name: mailpit
    ports:
      - "8025:8025"  # Web interface
      - "1025:1025"  # SMTP Port
    restart: unless-stopped

  # Service MySQL
  database:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_DATABASE: ${MYSQL_DB:-app}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-!ChangeMe!}
      MYSQL_USER: ${MYSQL_USER:-app}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-!ChangeMe!}
    ports:
      - "3306:3306"  # Expose MySQL port
    volumes:
      - database_data:/var/lib/mysql:rw                   
    restart: always

  # Service phpMyAdmin pour gérer MySQL via un navigateur
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql-db       # Nom du service MySQL
      PMA_USER: app            # Utilisateur MySQL
      PMA_PASSWORD: "!ChangeMe!" # Mot de passe de l'utilisateur MySQL
    ports:
      - "8080:80"  # Expose phpMyAdmin sur le port 8080
    restart: always

  gitlab:
    image: gitlab/gitlab-ce:latest
    restart: always
    hostname: 'gitlab.example.com'
    ports:
      - "8929:80"
    volumes:
      - './config:/etc/gitlab'
      - './logs:/var/log/gitlab'
      - './data:/var/opt/gitlab'
      
  app:
    image: node:18
    container_name: node-app
    volumes:
      - node:/usr/src/app
    working_dir: /usr/src/app
    command: node
    stdin_open: true
    tty: true


volumes:
  node:
  database_data:
